Assessment.WebApi/Models/ErrorViewModel.cs
namespace Assessment.WebApi.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Assessment.WebApi/Controllers/ChannelEngineController.cs
using Assessment.Business.Services.OrderService;
using Assessment.WebApi.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Assessment.WebApi.Controllers
{
    public class ChannelEngineController : Controller
    {
        private readonly IOrderService _orderService;

        public ChannelEngineController(IOrderService orderService)
        {
            _orderService = orderService;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }
        
        public IActionResult PrivacyTwo()
        {
            return View();
        }

        public IActionResult TopFiveProducts()
        {
            var topFiveSoldProducts = _orderService.GetTopFiveProductsSold();

            return View(topFiveSoldProducts);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Assessment.WebApi/Views/ChannelEngine/Index.cshtml
@{
    ViewData["Title"] = "Welcome Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome to C# Assessment</h1>
    <p>Use navigation bar for required functionality</p>
</div>

Assessment.WebApi/Views/ChannelEngine/TopFiveProducts.cshtml
@using Assessment.Domain.Models;
@model List<Product>

<link rel="stylesheet" href="~/css/topFiveProducts.css" asp-append-version="true" />

<table>
    <thead>
        <tr>
            <th>Name</th>
            <th>EAN</th>
            <th>Quantity</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var product in Model)
        {
            <tr>
                <td>@product.Name</td>
                <td>@(string.IsNullOrEmpty(product.Ean) ? "N/A" : product.Ean)</td>
                <td>@product.TotalQuantity</td>
            </tr>
        }
    </tbody>
</table>

Assessment.WebApi/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Assessment.WebApi</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Assessment.WebApi.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="ChannelEngine" asp-action="Index">C# Assessment</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ChannelEngine" asp-action="Index">Assessment Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ChannelEngine" asp-action="TopFiveProducts">Top 5 products</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>